### ISSUE TITLE
Bungee Shade triple render on iOS Safari (and others) 

### ISSUE THREAD

**Issue by lfinsaas** [djrrb/Bungee#100]
Hi folks,

First off, big fan of Bungee! Thanks for all your work on this project.

We're running into an issue where Bungee Shade is rendering the inline strokes three times. We've checked our code, internal and external devs, and it appears that the issue is within the font itself? 

Check it out yourself on iOS Safari: https://from-scratch.net/. 

There seems to be something with the viewport, too. Untouched, we can see the repeated inline strokes. When you zoom in, the issue resolves. Maybe something to do with retina? 

We're all scratching our heads over here. Let us know if there's something we're missing or anything else we can do to get the font to render properly!

Luke Finsaas

![shade on iPhone](https://github.com/djrrb/Bungee/assets/36778320/da436afb-6ec7-4d82-8c76-5c06271b79c2)

![shade on iOS Arc browser](https://github.com/djrrb/Bungee/assets/36778320/c6df3607-6bfb-4233-9c96-e6f74dd8ec21)

![shade on iPad](https://github.com/djrrb/Bungee/assets/36778320/a67be3d7-c54b-4d73-91f0-f399dda7cd60)

**Comment by djrrb** [comment]
Just a quick message without looking closely: I’m wondering if the font is getting [faux-bolded](https://alistapart.com/article/say-no-to-faux-bold/)... try removing `font-weight: bold` from the CSS element, or adding `font-synthesis: none` and see if that helps?

**Comment by djrrb** [comment]
And btw...thanks for using Bungee! The site looks great :-D

**Comment by lfinsaas** [comment]
That makes a lot of sense! We'll implement tomorrow and report back!

**Comment by sneakinhysteria** [comment]
@djrrb Thanks David, unfortunately the issue remains after removing “bold” and any indication of font weight

**Comment by djrrb** [comment]
Ah, most user stylesheets will make `<h1>` bold by default, so even though you do not set `font-weight: bold` explicitly it is still bolded. (The “your message” in the title is also getting faux-bolded, the effect is just more subtle.)

So the two easiest solutions are:

— to explicitly set your `<h1>` to `font-weight: normal;` 
and/or
— to avoid any chance of faux-bolding by using `font-synthesis: none;` 

Here is a codepen and the results I get in Safari on iPad: https://codepen.io/djrrb/pen/OJdPBbE

![IMG_CE20DE67E832-1](https://github.com/djrrb/Bungee/assets/6578861/1afb049b-d66f-4043-ba08-febd8254b5fa)

If for some reason you don’t want to change the styling of the page, you can also fix this by adding `font-weight: bold` to your @font-face calls, so that Bungee loads as Bold instead of Regular.

Hope that helps!

**Comment by sneakinhysteria** [comment]
Thanks so much for the quick and comprehensive reply. Forwarded to our devs. On 24 Oct 2023, at 14:25, David Jonathan Ross ***@***.***> wrote:OJdPBbE

**Comment by sneakinhysteria** [comment]
Fixed, thanks for your help! On 24 Oct 2023, at 14:25, David Jonathan Ross ***@***.***> wrote:﻿
Ah, most user stylesheets will make <h1> bold by default, so even though you do not set font-weight: bold explicitly it is still bolded. (The “your message” in the title is also getting faux-bolded, the effect is just more subtle.)
So the two easiest solutions are:
— to explicitly set your <h1> to font-weight: normal;
and/or
— to avoid any chance of faux-bolding by using font-synthesis: none;
Here is a codepen and the results I get in Safari on iPad: https://codepen.io/djrrb/pen/OJdPBbE

If for some reason you don’t want to change the styling of the page, you can also fix this by adding font-weight: bold to your @font-face calls, so that Bungee loads as Bold instead of Regular.
Hope that helps!
