### ISSUE TITLE
Bungee Hairline: glyphs with no contours

### ISSUE THREAD

**Issue by vv-monsalve** [djrrb/Bungee#113]
Hi @justvanrossum, the following glyphs do not have any contours at all. However, they have an AdvanceWidth of `1000`
Please confirm this is intended. This was reported in [#7795](https://github.com/google/fonts/pull/7795)

<details>
<summary>🔥 <b>FAIL</b> Check if each glyph has the recommended amount of contours. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/universal.html#"></a></summary>
🔥 **FAIL** <p>The following glyphs have no contours even though they were expected to have some:</p>
<pre><code>- Glyph name: whiteuppointingtriangle	Expected: 2

- Glyph name: whiterightpointingtriangle	Expected: 2

- Glyph name: whitedownpointingtriangle	Expected: 2

- Glyph name: whiteleftpointingtriangle	Expected: 2
</code></pre>
 [code: no-contour]
</details>

**Comment by justvanrossum** [comment]
I'm pretty sure this is intended, probably for layering. In any case, it matches the old fonts.

**Comment by vv-monsalve** [comment]
The previous Hairline font also had these glyphs empty. However, all the other fonts include outlines. I opened this issue to confirm if Hairline should also have them. 

Perhaps this is more of a question for @djrrb, wdyt?

<img width="376" alt="Screen Shot 2024-06-04 at 10 57 04" src="https://github.com/djrrb/Bungee/assets/48698976/25c64e8b-815c-45a1-8da6-d45f3b249347">
<img width="359" alt="Screen Shot 2024-06-04 at 10 57 49" src="https://github.com/djrrb/Bungee/assets/48698976/64f1121d-97a5-4832-95a1-34bacc5bdf59">
<img width="388" alt="Screen Shot 2024-06-04 at 10 58 17" src="https://github.com/djrrb/Bungee/assets/48698976/80cbb332-549a-4683-9232-7cabdc2f9336">

**Comment by djrrb** [comment]
Just is correct...the empty glyphs in Bungee Hairline was intentional, and intended for layering. These glyphs are too thin/complex to have anything going on inside them.

As Just says, this matches the old fonts and is not a regression, so I see no need for it to hold up a submission to GF. 

I acknowledge that an empty character is not an ideal outcome if the Hairline is used on its own and not in layering. I’m not sure I have a better solution though...if we simply copy the outlines from Bungee Regular into Bungee Hairline, we would create a regression when the fonts are used in layering. And if we remove the glyphs from Bungee Hairline, not only would we create a regression in layering but we’d also cause the styles of Bungee to have inconsistent character coverage...which I’m guessing is a fontbakery fail? 

I am open to your opinions on this, but my feeling is that it is okay to let this stand, since it only affects a small subset of characters, and is consistent with other unusual decisions in the Hairline font, such as the fact that the letters do not sit on the baseline. 

Eventually, I would love to make a true Hairline weight for Bungee that is part of a conventional weight axis, which would not be constrained by the limitations of layering, and could contain proper hairline versions of these characters.

Below is a full list of glyphs that I believe are affected:

```
uni261A
uni261B
indexup
indexdown
indexupleft
indexupright
indexdownleft
indexdownright
uni261C
uni261D
uni261E
uni261F
indexdownleft.outline
indexdownright.outline
indexupleft.outline
indexupright.outline
uni261A.salt
uni261B.salt
indexdown.salt
indexdownleft.salt
indexdownright.salt
indexup.salt
indexupleft.salt
indexupright.salt
uni261C.salt
uni261D.salt
uni261E.salt
uni261F.salt
indexdownleft.salt_outline
indexdownright.salt_outline
indexupleft.salt_outline
indexupright.salt_outline
whiteuppointingtriangle
whitedownpointingtriangle
whiteleftpointingtriangle
whiterightpointingtriangle
```

**Comment by vv-monsalve** [comment]
> I acknowledge that an empty character is not an ideal outcome if the Hairline is used on its own and not in layering.

This was the main concern in opening this issue and confirming these glyphs.

However, the reasoning behind the empty glyphs on this variant is now clearer, thank you!. There's no need to change the font, then. We'll continue with it as is now.

> Eventually, I would love to make a true Hairline weight for Bungee that is part of a conventional weight axis, which would not be constrained by the limitations of layering, and could contain proper hairline versions of these characters.

This would be a great addition indeed!
