### ISSUE TITLE
Releases seems weird

### ISSUE THREAD

**Issue by davelab6** [djrrb/Bungee#58]
<img width="1037" alt="screen shot 2016-11-05 at 16 06 46" src="https://cloud.githubusercontent.com/assets/261579/20033197/e3a46c68-a371-11e6-9d6c-f1f3f42d33da.png">

❓

**Comment by RoelN** [comment]
There's a new directory `Bungee_Basic` and an extra WOFF and WOFF2 of the OpenType SVG font — if you're referring to the increase in size.

**Comment by djrrb** [comment]
And if you're talking about the dates...I think that is due to me changing the release number from 1.0 to 1.0.0 so it would be consistent with [semantic versioning](http://semver.org). Didn't realize it would update the dates, or that I inadvertently changed the folder structure. Oy.

I'm hoping I can fix #53 and just issue a new one. Would that make things better?

**Comment by davelab6** [comment]
> if you're talking about the dates

Yes

> you're referring to the increase in size

No :)

> I'm hoping I can fix #53 and just issue a new one. Would that make things better?

I guess so =)
